spring:
  application:
    name: appointment_history_service

  rabbitmq:
    host: rabbitmq
    port: 5671
    username: guest
    password: guest
    ssl:
      enabled: true
      algorithm: TLSv1.2
      validate-server-certificate: true
      key-store: classpath:rabbitmq/client_keystore.p12  # convert client.key+client.crt into PKCS12
      key-store-password: changeit
      trust-store: classpath:rabbitmq/truststore.p12     # contains CA cert
      trust-store-password: changeit

  datasource:
    url: ${HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_APPOINTMENT_HISTORY_SERVICE_DB_DIALECT}
    show-sql: true
